feat: !が先頭にあるメッセージはAdminChatから除外するように
AzisabaNetwork/VanilifeCore pull request #11
Opened 2022-07-31 17:09 UTC by m2en

AdminChat 有効中 `!` が先頭についたメッセージはAdminChatから除外します。

2022-07-31 19:17 UTC, acrylic-style commented on src/main/java/net/azisaba/vanilife/core/listeners/AdminChatListener.java
> +      if(e.message().toString().startsWith("!")) {
PlaintextComponentSerializer?

2022-08-10 06:24 UTC, m2en commented on src/main/java/net/azisaba/vanilife/core/listeners/AdminChatListener.java
> +      if(e.message().toString().startsWith("!")) {
maybe, そう

2022-08-10 07:56 UTC, acrylic-style requested changes
意味が伝わってなかったのでsuggest

2022-08-10 07:56 UTC, acrylic-style commented on src/main/java/net/azisaba/vanilife/core/listeners/AdminChatListener.java
> +      if(e.message().toString().startsWith("!")) {
```suggestion
      if (PlainTextComponentSerializer.plainText().serialize(e.message()).startsWith("!")) {
```

2022-08-14 07:04 UTC, m2en commented
what

2022-08-14 07:19 UTC, acrylic-style approved these changes

2022-08-14 07:20 UTC, merged