fix #12
AzisabaNetwork/VanilifeCore pull request #13
Opened 2022-08-24 05:23 UTC by Propromp

close #12

2022-08-24 05:38 UTC, m2en requested changes

2022-08-24 05:38 UTC, m2en commented on src/main/java/net/azisaba/vanilife/core/listeners/AdminChatListener.java
> +      var plainMessage = PlainTextComponentSerializer.plainText().serialize(e.message());
ここでは `var` を使ってないと思うので揃えてくれると嬉しい

2022-08-24 06:59 UTC, Propromp commented on src/main/java/net/azisaba/vanilife/core/listeners/AdminChatListener.java
> +      var plainMessage = PlainTextComponentSerializer.plainText().serialize(e.message());
varを使うなってこと？

2022-08-24 12:56 UTC, m2en commented on src/main/java/net/azisaba/vanilife/core/listeners/AdminChatListener.java
> +      var plainMessage = PlainTextComponentSerializer.plainText().serialize(e.message());
> varを使うなってこと？

そう
VanilifeCore内では多分 `var` で宣言一度もしてないと思うから

2022-08-25 08:25 UTC, m2en approved these changes

2022-08-25 08:27 UTC, merged